# Generated by Django 5.2.6 on 2025-12-31 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarotistas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('duracion', models.PositiveIntegerField(default=60)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_cliente', to=settings.AUTH_USER_MODEL)),
                ('tarotista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_tarotista', to='tarotistas.tarotista')),
            ],
            options={
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['tarotista', 'fecha_hora'], name='citas_cita_tarotis_67e7bf_idx')],
                'constraints': [models.UniqueConstraint(fields=('tarotista', 'fecha_hora'), name='unique_cita_tarotista_fecha')],
            },
        ),
    ]

