# Generated by Django 5.2.6 on 2025-12-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('basico', 'Tarot Básico'), ('completo', 'Tarot Completo'), ('amor', 'Tarot del Amor'), ('karmico', 'Tarot Kármico')], default='basico', max_length=20),
        ),
    ]
